name: Richard Parkes
favicon: null
layout_spectrum: 0.25357
typography_spectrum: 0.07293
title: 'Richard Parkes - Random website, with no purpose'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3e0ff'
    - '#496f40'
    - '#b49372'
    - '#483f36'
    - '#291b1a'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
