name: Richard Parkes
favicon: null
layout_spectrum: 0.16686
typography_spectrum: 0.58164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d001c'
    - '#a1001f'
    - '#d4c19c'
    - '#aa6645'
    - '#fdfefa'
  brandStrength: 0.25
  lightness: 0.9375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
