name: Richard Parkes
favicon: null
layout_spectrum: 0.50053
typography_spectrum: 0.9010680152568966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d001c'
    - '#9d001d'
    - '#cfcba3'
    - '#8d4c31'
    - '#fefdeb'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
