name: Richard Parkes
favicon: null
layout_spectrum: 0.25357
typography_spectrum: 0.07293
title: 'Richard Parkes - Random website, with no purpose'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5580a3'
    - '#412f17'
    - '#c3cbd1'
    - '#d95b6b'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
