name: Richard Parkes
favicon: null
layout_spectrum: 0.48629
typography_spectrum: 0.58164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d001c'
    - '#9d001d'
    - '#cfcba3'
    - '#8d4c31'
    - '#fefdeb'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
