name: Richard Parkes
favicon: null
layout_spectrum: 0.026474806014448404
typography_spectrum: 0.9010680152568966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.11351630184799433
  lightness: 0.42188918334431946
  saturation: 0.9535314964596182
  rhythmicContrast: 0.8201645324006677
purpose: []
