name: Richard Parkes
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: 'Richard Parkes - Random website, with no purpose'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefffd'
    - '#0e100d'
    - '#747162'
    - '#01fffd'
    - '#0093fb'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
