name: Richard Parkes
favicon: null
layout_spectrum: 0.25357
typography_spectrum: 0.46567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5580a3'
    - '#412f17'
    - '#c3cbd1'
    - '#d95b6b'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
